name: ai_nutritionist_flutter
description: AI Nutritionist Flutter App
version: 1.0.0+1
publish_to: 'none'

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  http: ^1.3.0
  google_fonts: ^6.1.0
  flutter_native_splash: ^2.4.4
  animated_text_kit: ^4.2.2
  provider: ^6.1.2
  flutter_dotenv: ^5.1.0
  flutter_tts: ^4.2.2  # ✅ Added for Text-to-Speech
  shared_preferences: ^2.2.2
  speech_to_text: ^7.0.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.3

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
    - assets/.env
    - assets/logo.png


# Optional custom font setup
# fonts:
#   - family: SFPro
#     fonts:
#       - asset: assets/fonts/SFProDisplay-Regular.otf
#       - asset: assets/fonts/SFProDisplay-Medium.otf
#       - asset: assets/fonts/SFProDisplay-Bold.otf
#         weight: 700

flutter_native_splash:
  color: "#ffffff"
  image: assets/images/splash_logo.png
  branding: assets/images/branding.png
  branding_mode: bottom
  android_gravity: center
  ios_content_mode: center
  fullscreen: true

flutter_icons:
  android: true
  ios: true
  image_path: assets/logo.png
